import React from 'react';
import Head from 'next/head';
import { Provider } from 'react-redux';

import store from '../swapi/store';
import MillenniumFalconConnected from '../swapi/components/millennium-falcon-connected';
import OwnedEntitiesDisplay from '../swapi/components/owned-entities-display';
import SabersClicker from '../swapi/components/sabers-clicker';

export default class ReduxPage extends React.PureComponent {
	render() {
		return (
			<Provider store={store}>
				<div>
					<Head>
						<title>Fun With Redux</title>
						<meta
							name="viewport"
							content="initial-scale=1.0, width=device-width"
						/>
						<link
							rel="stylesheet"
							href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
							type="text/css"
						/>
						<link
							rel="stylesheet"
							href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
							type="text/css"
						/>
						<link href="/static/styles.css" rel="stylesheet" />
					</Head>
					<div className="container">
						<h1>
							Lots of fun with Redux
							<small> Also known as the Star Wars cookie-clicker clone</small>
						</h1>
						<div className="row">
							<p className="lead">
								Collect money, buy new characters, and load them up into ships
								to your hearts desire.
							</p>
							<p>
								Character value is based on their mass, and generate credits
								based on their height.
							</p>
							<p>
								Starships with crew members inside, multiply the credits
								generated by characters by the ships maximum atmospheric speed.
							</p>
						</div>
						<div className="row">
							<div className="col-md-2 saber-clicker">
								<SabersClicker />
							</div>
							<div className="col-md-6">
								<MillenniumFalconConnected />
							</div>
							<div className="col-md-4">
								<OwnedEntitiesDisplay />
							</div>
						</div>
					</div>
				</div>
			</Provider>
		);
	}
}
